### ISSUE TITLE
Support for GDAL 2.4?

### ISSUE THREAD

**Issue by axelande** [CSIRO-Precision-Agriculture/PAT_QGIS_Plugin#11]
Would it be possible to open up for support of GDAL 2.4? It is a little bit tricky to install GDAL 2.3, since it is 2.4 that is shipped with QGIS 2.18.28.

**Comment by cratcliff** [comment]
Yes. Current version works using QGIS 2.18.26 which uses gdal 2.3.2
This dependency is coming from using RasterIO which causes an error in windows when a newer version of GDAL is released. 
I am in the process of upgrading to support rasterio 1.0.18 and GDAL 2.4.

**Comment by axelande** [comment]
I believe that Fiona also is dependent on the GDAL version, so I assume that you have to upgrade the wheel for Fiona as well?

**Comment by cratcliff** [comment]
Yes Fiona is dependent on GDAL but fiona 1.8.4 is still the most up to date wheel.
Rasterio for windows is the problem. It doesn't handle a GDAL update as nicely.

**Comment by cratcliff** [comment]
This will be completed as part of the upgrade to QGIS 3 and Python3

**Comment by cratcliff** [comment]
As a version of PAT to support QGIS 3 is expected July 2020 I am closing this issue.
