### ISSUE TITLE
Installation or updates are required for qgis_customwidgets.

### ISSUE THREAD

**Issue by bastueste** [CSIRO-Precision-Agriculture/PAT_QGIS_Plugin#41]
Hi, 
I wanted to install the PAT Plugin on Qgis, but it doesnt work. When I do the steps described in the manual and I want to open Qgis an error occured. "Installation or updates are required for qgis_customwidgets" Maybe you have an Idea, how to solve this isssue?
Many thanks

**Comment by cratcliff** [comment]
@bastueste what version of QGIS are you using? 
Can you add a screen grab of the error the error? 
Is this before or after running the BAT file?

**Comment by bastueste** [comment]
Hi, 
thanks for your reply.
Versionnumber 2.18.25 
Its after running the BAT file (Install PAT Extra). 
Kind regards
 
 
-----Ursprüngliche Mitteilung-----
Von: Christina Ratcliff <notifications@github.com>
An: CSIRO-Precision-Agriculture/PAT_QGIS_Plugin <PAT_QGIS_Plugin@noreply.github.com>
Cc: bastueste <bastueste@aol.com>; Mention <mention@noreply.github.com>
Verschickt: Mi, 13. Mai 2020 8:29
Betreff: Re: [CSIRO-Precision-Agriculture/PAT_QGIS_Plugin] Installation or updates are required for qgis_customwidgets. (#41)

@bastueste what version of QGIS are you using?
Can you add a screen grab of the error the error?
Is this before or after running the BAT file?—

**Comment by bastueste** [comment]
![failbastueste2](https://user-images.githubusercontent.com/65223181/81832680-15d54c80-953f-11ea-91cf-b72f4ef647ea.png)
![failbastueste](https://user-images.githubusercontent.com/65223181/81832690-1968d380-953f-11ea-80e2-e0e0d060015b.png)

**Comment by cratcliff** [comment]
@bastueste could you please locate and email the Install_PAT_Extras.bat file to PAT@csiro.au. It should be in a folder like C:\Users\XXXX\.qgis2\python\plugins\pat\python_packages where XXXX is your username. 

Could you also add to the email, the path to the qgis_customwidgets.py file. It should be in a folder similar to "C:\Program Files\QGIS 2.18\apps\qgis-ltr\python\PyQt4\uic\widget-plugins"

**Comment by cratcliff** [comment]
For others experiencing this issue just copy 
    `C:\Program Files\QGIS 2.18\apps\qgis-ltr\python\PyQt4\uic\widget-plugins\qgis_customwidgets.py`
into 
`C:\Program Files\QGIS 2.18\apps\Python27\Lib\site-packages\PyQt4\uic\widget-plugins`
