### ISSUE TITLE
Cannot install PAT plugin

### ISSUE THREAD

**Issue by FredericFournier** [CSIRO-Precision-Agriculture/PAT_QGIS_Plugin#62]
Hi, when I install the latest versions of QGIS (3,20 +)  using the OSGeo4W Network installer or the QGIS standalone installer, I am not able to fully install the PAT3 extras. In the process it  removes the qgis_app.dll file and therefore I cannot use QGIS. 
I have been able to install some of the extras individually (fiona, geopandas, pyprecag) using the OSGeo4W network but I am not able to install gdal300.dll.

Can PAT plugin run with the newests versions of QGIS 3.20 +

Thank you for your help.

Fred

**Comment by cratcliff** [comment]
@FredericFournier there is a problem with the installation at the moment and I expect to release a new version this week.

**Comment by carlaohws** [comment]
Hi, I have the same problem as @FredericFournier, do you have a release date of the corrected version?

**Comment by JRichetti** [comment]
Hi @cratcliff , any updates here? I've tried to install on QGIS 3.18.1 and I'm getting the classFactory() error. Same for QGIS 3.22

**Comment by cratcliff** [comment]
@carlaohws @JRichetti @FredericFournier I have just released a new version in the QGIS plugin manager. Can you please try it and let me know of any problems.

**Comment by FredericFournier** [comment]
Hi Christina,

Good, I will try it and let you know if it all works well.

Thank you very much.

Frédéric Fournier, biol et agr.
Cellulaire : 581 984-7120

***@***.***

De : Christina Ratcliff ***@***.***>
Envoyé : 14 octobre 2022 01:07
À : CSIRO-Precision-Agriculture/PAT_QGIS_Plugin ***@***.***>
Cc : FredericFournier ***@***.***>; Mention ***@***.***>
Objet : Re: [CSIRO-Precision-Agriculture/PAT_QGIS_Plugin] Cannot install PAT plugin (Issue #62)


@carlaohws<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcarlaohws&data=05%7C01%7C%7Cb4d8464c3f9b4e89ecf308daada1fa66%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638013208468696665%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DnSHw46oCOwdzAI0GOYe6olEWN0Xg3mHzgp7czh5U3I%3D&reserved=0> @JRichetti<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJRichetti&data=05%7C01%7C%7Cb4d8464c3f9b4e89ecf308daada1fa66%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638013208468696665%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sksol64hDQXNnZgZJsoJ6Ag1A5sDrb57qVpd1bR6E1g%3D&reserved=0> @FredericFournier<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFredericFournier&data=05%7C01%7C%7Cb4d8464c3f9b4e89ecf308daada1fa66%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638013208468696665%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oELBatlLj%2BwVLjWums5S52g38zRWPqGMYsODCemx2XE%3D&reserved=0> I have just released a new version in the QGIS plugin manager. Can you please try it and let me know of any problems.

-
