### ISSUE TITLE
Cannot install PAT plugin the Install_PAT3_Extras cant finish instalation

### ISSUE THREAD

**Issue by aleksyaremenko** [CSIRO-Precision-Agriculture/PAT_QGIS_Plugin#63]
Can not install PAT plugin on my laptop 
Tried different versions of QGIS, but when I run as Administrator Install_Pat dependencies always the same mistake 
Also, the shortcut  Install_PAT_Extras doesn`t appear on the desctop, it is not a problem for me I found the file  Install_PAT_Extras.bat, but maybe it is important
Windows 10 

install dependencies for QGIS PAT Plugin.... Please Wait
Dependencies Log: C:\Users\user\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pat\install_files\dependency_2022-08-07.log
'"C:\PROGRA~1\bin\py3_env.bat"' is not recognized as an internal or external command,
operable program or batch file.
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
 Running "C:\Program Files\bin\o4w_env.bat"
 Running "C:\PROGRA~1\bin\py3_env.bat"

Osgeo4w Installing -P gdal300dll, -P python3-fiona, -P python3-geopandas, -P python3-rasterio -----------------------------------------------
ECHO is off.
Starting OSGeo4W install, version 2.579
using locales .1251
io_stream_cygfile: fopen(/etc/setup/setup.rc) failed 2 No such file or directory
Current Directory: C:\Users\user\AppData\Local\Temp
Root Directory: C:\Program Files
Could not open service McShield for query, start and stop. McAfee may not be installed, or we don't have access.
mbox yesno: ═х Ёхъюьхэфє║Є№ё  тшъюЁшёЄютєтрЄш °ы ї, ∙ю ь│ёЄшЄ№ яЁюс│ыш є эрчт│ яряюъ. ╧ЁюфютцшЄш?
unattended_mode is set at mbox: returning default value
root: C:\Program Files
Selected local directory: C:\Users\user\AppData\Local\Temp
Menu name: OSGeo4W
net: Preconfig
Cached mirror list unavailable
get_url_to_membuf https://download.osgeo.org/osgeo4w/ssl/mirrors.lst
getUrlToStream https://download.osgeo.org/osgeo4w/ssl/mirrors.lst
User-Agent: default is "OSGeo4W-Setup/2.579 (Windows NT 6.2.9200;Win64;0422)"
Request for URL https://download.osgeo.org/osgeo4w/ssl/mirrors.lst satisfied from cache
site: http://download.osgeo.org/osgeo4w/
get_url_to_membuf http://download.osgeo.org/osgeo4w/x86_64/setup.ini.bz2
getUrlToStream http://download.osgeo.org/osgeo4w/x86_64/setup.ini.bz2
HTTP status 404 fetching http://download.osgeo.org/osgeo4w/x86_64/setup.ini.bz2
getUrlToStream failed!
get_url_to_membuf failed!
get_url_to_membuf http://download.osgeo.org/osgeo4w/x86_64/setup.ini
getUrlToStream http://download.osgeo.org/osgeo4w/x86_64/setup.ini
HTTP status 404 fetching http://download.osgeo.org/osgeo4w/x86_64/setup.ini
getUrlToStream failed!
get_url_to_membuf failed!
mbox note: ═хьюцыштю юЄЁшьрЄш setup.ini ч <http://download.osgeo.org/osgeo4w/>
unattended_mode is set at mbox: returning default value
site: http://download.osgeo.org/osgeo4w/
get_url_to_membuf http://download.osgeo.org/osgeo4w/x86_64/setup.ini.bz2
getUrlToStream http://download.osgeo.org/osgeo4w/x86_64/setup.ini.bz2
HTTP status 404 fetching http://download.osgeo.org/osgeo4w/x86_64/setup.ini.bz2
getUrlToStream failed!
get_url_to_membuf failed!
get_url_to_membuf http://download.osgeo.org/osgeo4w/x86_64/setup.ini
getUrlToStream http://download.osgeo.org/osgeo4w/x86_64/setup.ini
HTTP status 404 fetching http://download.osgeo.org/osgeo4w/x86_64/setup.ini
getUrlToStream failed!
get_url_to_membuf failed!
mbox note: ═хьюцыштю юЄЁшьрЄш setup.ini ч <http://download.osgeo.org/osgeo4w/>
unattended_mode is set at mbox: returning default value
site: http://download.osgeo.org/osgeo4w/
get_url_to_membuf http://download.osgeo.org/osgeo4w/x86_64/setup.ini.bz2
getUrlToStream http://download.osgeo.org/osgeo4w/x86_64/setup.ini.bz2
HTTP status 404 fetching http://download.osgeo.org/osgeo4w/x86_64/setup.ini.bz2
getUrlToStream failed!
get_url_to_membuf failed!
get_url_to_membuf http://download.osgeo.org/osgeo4w/x86_64/setup.ini
getUrlToStream http://download.osgeo.org/osgeo4w/x86_64/setup.ini
HTTP status 404 fetching http://download.osgeo.org/osgeo4w/x86_64/setup.ini
getUrlToStream failed!
get_url_to_membuf failed!
mbox note: ═хьюцыштю юЄЁшьрЄш setup.ini ч <http://download.osgeo.org/osgeo4w/>
unattended_mode is set at mbox: returning default value
site: http://download.osgeo.org/osgeo4w/
get_url_to_membuf http://download.osgeo.org/osgeo4w/x86_64/setup.ini.bz2
getUrlToStream http://download.osgeo.org/osgeo4w/x86_64/setup.ini.bz2
HTTP status 404 fetching http://download.osgeo.org/osgeo4w/x86_64/setup.ini.bz2
getUrlToStream failed!
get_url_to_membuf failed!
get_url_to_membuf http://download.osgeo.org/osgeo4w/x86_64/setup.ini
getUrlToStream http://download.osgeo.org/osgeo4w/x86_64/setup.ini
HTTP status 404 fetching http://download.osgeo.org/osgeo4w/x86_64/setup.ini
getUrlToStream failed!
get_url_to_membuf failed!
mbox note: ═хьюцыштю юЄЁшьрЄш setup.ini ч <http://download.osgeo.org/osgeo4w/>
unattended_mode is set at mbox: returning default value
site: http://download.osgeo.org/osgeo4w/
get_url_to_membuf http://download.osgeo.org/osgeo4w/x86_64/setup.ini.bz2
getUrlToStream http://download.osgeo.org/osgeo4w/x86_64/setup.ini.bz2
HTTP status 404 fetching http://download.osgeo.org/osgeo4w/x86_64/setup.ini.bz2
getUrlToStream failed!
get_url_to_membuf failed!
get_url_to_membuf http://download.osgeo.org/osgeo4w/x86_64/setup.ini
getUrlToStream http://download.osgeo.org/osgeo4w/x86_64/setup.ini
HTTP status 404 fetching http://download.osgeo.org/osgeo4w/x86_64/setup.ini
getUrlToStream failed!
get_url_to_membuf failed!
mbox note: ═хьюцыштю юЄЁшьрЄш setup.ini ч <http://download.osgeo.org/osgeo4w/>
unattended_mode is set at mbox: returning default value
download/verify error in unattended_mode: out of retries
note: ┬ёЄрэютыхээ  эх чртхЁ°хэю. ─шт│Є№ё  C:\Program Files\setup.log.full ∙юс юЄЁшьрЄш с│ы№°х │эЇюЁьрЎ│┐.
Ending OSGeo4W install

The current directory is C:\Users\user\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pat\install_files

PIP install  pyprecag -----------------------------------------------
Collecting pyprecag
  Downloading pyprecag-0.4.0.tar.gz (14.0 MB)
     --------------------------------------- 14.0/14.0 MB 12.1 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: future in c:\program files\apps\python39\lib\site-packages (from pyprecag) (0.18.2)
Requirement already satisfied: scipy in c:\program files\apps\python39\lib\site-packages (from pyprecag) (1.6.2)
Collecting fiona
  Downloading Fiona-1.8.21.tar.gz (1.0 MB)
     ---------------------------------------- 1.0/1.0 MB 11.0 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

----------------------------------------------------------------------

** Please restart QGIS to complete installation.
You may have to reinstall or activate the PAT Plugin through the plugin manager.

Press any key to continue . . .

**Comment by agiudiceandrea** [comment]
Looking at the log you published in the issue report, it seems to me the plugin mechanism to install the dependencies is not correctly adapted to the new OSGeo4W installation infrastructure.
In fact, the py3_env.bat batch file called in the Install_PAT_Extras.bat batch file is no longer available and no longer needed with the latest OSGeo4W installers. Moreover, the URL http://download.osgeo.org/osgeo4w/ used in the Install_PAT_Extras.bat batch file is outdated: the new URL is https://download.osgeo.org/osgeo4w/v2/ (if you are using the latest QGIS version) or https://download.osgeo.org/osgeo4w/v1/ (if you are using outdated QGIS versions.

**Comment by cratcliff** [comment]
@agiudiceandrea thanks for the information. Do you by any chance use OneDrive? I am currently looking at errors with the install for OneDrive users in the process of fixing other install issues.

**Comment by aleksyaremenko** [comment]
I am not using OneDrive at all, even delete it from my laptop, but OneDrive was installed by default with the installation operational system, so it could influence. 
Any recommendation now, on how I could install the plugin? 
If install the needed packages by myself using the OSGeo4W Setup and then installing the plugin could solve the problem?
And which version of QGIS is better to use?

**Comment by agiudiceandrea** [comment]
> Do you by any chance use OneDrive?

Hi @cratcliff, I'm not using OneDrive.

**Comment by aleksyaremenko** [comment]
Hi @cratcliff 
Do you have any recommendations about installation or news on how soon the updates may be released?
Really need to use the plugin(

**Comment by cratcliff** [comment]
@aleksyaremenko I hope to release it later this week or early next week.

**Comment by aleksyaremenko** [comment]
Thank you @cratcliff 
I am really looking forward to it

**Comment by aleksyaremenko** [comment]
> @aleksyaremenko I hope to release it later this week or early next week.

Hi, @cratcliff 
sorry, that I`m annoying, but is any news about the new release? 
thank you :)

**Comment by cratcliff** [comment]
@aleksyaremenko I do have a beta version I can email you. Can you send an email to address shown on page two of the user manual, or by clicking on the author name in the PAT record in the QGIS plugin manager.

**Comment by aleksyaremenko** [comment]
@cratcliff Done

**Comment by agiudiceandrea** [comment]
@aleksyaremenko, why have you closed this issue?

**Comment by aleksyaremenko** [comment]
@cratcliff my issue was resolved by the version which you send me
